version: '3.8'

services:
  # ----------------------------------------------------------------
  # 1.  BASE DE DATOS 
  # ----------------------------------------------------------------
  mysql:
    image: mysql:8.0
    container_name: mysql_reservas
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reservas_db
      MYSQL_USER: reservas_user
      MYSQL_PASSWORD: reservas_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # ----------------------------------------------------------------
  # 2. N8N
  # ----------------------------------------------------------------
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n_reservas
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=America/Santiago
      - N8N_HOST=localhost
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      #  URL de Ngrok
      - WEBHOOK_URL=https://dinah-cacogenic-shauna.ngrok-free.dev/
    
    # IMPORTANTE: Esto permite que n8n vea tu Django (que corre en tu PC fuera de Docker)
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
    volumes:
      - n8n_data:/home/node/.n8n

# ----------------------------------------------------------------
# VOLÃšMENES (Declarados una sola vez al final)
# ----------------------------------------------------------------
volumes:
  mysql_data:
  n8n_data: